= Quarkus Bucket4j
:extension-status: experimental

include::./includes/attributes.adoc[]

Bucket4J is a Java rate-limiting library based on the token-bucket algorithm. Bucket4j is a thread-safe library that can be used in either a standalone JVM application, or a clustered environment. It also supports in-memory or distributed caching via the JCache (JSR107) specification.
This extension allow you to control the request rate sent to your application by using a dead simple API.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.bucket4j:quarkus-bucket4j` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.bucket4j</groupId>
    <artifactId>quarkus-bucket4j</artifactId>
    <version>{project-version}</version>
</dependency>
----

[#getting-started]
== Getting Started

=== Throttling a Method

Annotate the method that need to be throttled with @RateLimited

[source,java]
----
@ApplicationScoped
public static class RateLimitedMethods {

    @RateLimited(limitsKey = "group1")
    public String limited() {
        return "LIMITED";
    }

}
----

And add a limit group using the same limitsKey in the configuration:

[source,properties]
----
# burst protection
quarkus.rate-limiter.buckets.group1[0].max-usage: 10
quarkus.rate-limiter.buckets.group1[0].period: 1S
# fair use
quarkus.rate-limiter.buckets.group1[1].max-usage: 100
quarkus.rate-limiter.buckets.group1[1].period: 5M
----

or with yaml:

[source,yaml]
----
quarkus:
  rate-limiter:
    buckets:
      group1:
       - max-usage: 10
         period: 1S
       - max-usage: 100
         period: 5M
----

The bucket can contain multiple limits that will all be enforced.
If multiple methods share the same bucket, the number of allowed requests is shared for all them

=== Population Segmentation

If you want to enable throttling per user, simply specify an IdentityKeyResolver in the RateLimited annotation.
The default one is the ConstantResolver, which will cause the segmentation to be disabled.

[source,java]
----
@ApplicationScoped
public static class RateLimitedMethods {

    @RateLimited(limitsKey = "group1", identityResolver = IpResolver.class)
    public String limitedByIp() {
        return "LIMITED";
    }
}
----

IpResolver is provided out of the box. if you want a more complex segmentation, you can implement your own resolver.
A custom resolver must be a valid CDI Bean.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-bucket4j.adoc[leveloffset=+1, opts=optional]
